authority:  "www.cordcloud.one"
method:  "POST"
path:  "/user/checkin"
scheme:  "https"
Cookie:
Accept:  "application/json, text/javascript, */*; q=0.01"
Accept-Encoding:  ""
Accept-Language:  "zh-CN,zh-TW;q=0.9,zh;q=0.8,en;q=0.7"
Content-Length:  "0"
Origin:  "https://www.cordcloud.one"
Referer:  "https://www.cordcloud.one/user"
Sec-Fetch-Site:  "same-origin"
User-Agent:  "Mozilla/5.0 (Windows NT 10.0; Win64; x64 AppleWebKit/537.36 (KHTML, like Gecko Chrome/102.0.5005.63 Safari/537.36"
Sec-Fetch-Mode:  "cors"
Sec-Fetch-Dest:  "empty"
sec-ch-ua-platform:  "Windows"
sec-ch-ua:  .Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103
sec-ch-ua-mobile:  "?0"
X-Requested-With:  "XMLHttpRequest"