Accept: text/plain, */*; q=0.01
Accept-Encoding: ""
Accept-Language: zh-CN,zh-TW;q=0.9,zh;q=0.8,en;q=0.7
Connection: keep-alive
Content-Length: 43
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie:
Host: bbs.pediy.com
Origin: https://bbs.pediy.com
Referer: https://bbs.pediy.com/
sec-ch-ua: .Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
X-Requested-With: XMLHttpRequest